name: Create Release and Upload Deb Package

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with "v", e.g. v1.0rc1-1

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev debhelper build-essential fakeroot

      - name: Build Debian Package
        run: |
          dpkg-buildpackage -us -uc
          # Move the generated deb package from the parent directory into the workspace
          mv ../compbench_*.deb ./

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
          body: "Compbench release ${{ github.ref }} is now available!"

      - name: Upload Debian Package Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: compbench_*.deb
          asset_name: compbench.deb
          asset_content_type: application/x-debian-package
