name: Build Debian Package

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with "v"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev debhelper build-essential fakeroot

      - name: Build Debian Package
        run: dpkg-buildpackage -us -uc

      - name: Upload Debian Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compbench-deb
          path: ../compbench_*.deb
